name: Build Windows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Cache konan directory
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Windows build
        run: |
          ./gradlew mingwX64Test publishKotlinMultiplatformPublicationToMavenLocal publishMingwX64PublicationToMavenLocal --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"
